version: '3.1'

services:
  user-api:
    build: ./user-api/chat-user-api
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: database

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db-pass123
      MYSQL_DATABASE: chat-db
    volumes:
    - database-data:/var/lib/mysql

volumes:
  database-data: